// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXLe84o_qCTEHDx7UuBQVepYinmV5Tn6s',
    appId: '1:889753489592:web:cb85083d67df367ad1644d',
    messagingSenderId: '889753489592',
    projectId: 'kiti-30-07-2022',
    authDomain: 'kiti-30-07-2022.firebaseapp.com',
    databaseURL: 'https://kiti-30-07-2022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiti-30-07-2022.appspot.com',
    measurementId: 'G-3VMDG9M1KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5gPeHrXEpD_NP736_xrlXyt5fGcr9sHY',
    appId: '1:889753489592:android:8bbb20e676834a7bd1644d',
    messagingSenderId: '889753489592',
    projectId: 'kiti-30-07-2022',
    databaseURL: 'https://kiti-30-07-2022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiti-30-07-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMZfj8Y5K0xaz03VZ2xFc_5yVPQSAufyU',
    appId: '1:889753489592:ios:f2b239e1ce2573ffd1644d',
    messagingSenderId: '889753489592',
    projectId: 'kiti-30-07-2022',
    databaseURL: 'https://kiti-30-07-2022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiti-30-07-2022.appspot.com',
    iosClientId: '889753489592-5is2vd6ll7o4c54e5928sjbumjpjlgb7.apps.googleusercontent.com',
    iosBundleId: 'vn.at.app.kiti',
  );
}
