// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIhpQk07QqUAQUMWIZo1C3dATaD-ahn28',
    appId: '1:3476099839:web:86d87de4a13560f4d8b2ca',
    messagingSenderId: '3476099839',
    projectId: 'kiti-24-07-2022',
    authDomain: 'kiti-24-07-2022.firebaseapp.com',
    databaseURL: 'https://kiti-24-07-2022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiti-24-07-2022.appspot.com',
    measurementId: 'G-8BBJ96N0VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7wxNmzgiUXwlWVgFNkxTo5QPyRV-kU70',
    appId: '1:3476099839:android:2fc6acf3c16391b5d8b2ca',
    messagingSenderId: '3476099839',
    projectId: 'kiti-24-07-2022',
    databaseURL: 'https://kiti-24-07-2022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiti-24-07-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWwKk1DWzQmJsN8ZROfDnJXfTNPs7yBSM',
    appId: '1:3476099839:ios:e8761fecea463dacd8b2ca',
    messagingSenderId: '3476099839',
    projectId: 'kiti-24-07-2022',
    databaseURL: 'https://kiti-24-07-2022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiti-24-07-2022.appspot.com',
    iosClientId: '3476099839-rbkbhv5vgt68ma7k1ie5f6qfaq28032r.apps.googleusercontent.com',
    iosBundleId: 'vn.at.app.kiti',
  );
}
